code_folder = "/Users/mb/_deckard_code/"

[project.flutter]
icon = "ğŸ¦"
repo = "https://github.com/flutter/flutter"

[project.rust]
icon = "ğŸ§²"
repo = "https://github.com/rust-lang/rust"

[project.k8s]
icon = "ğŸš€"
repo = "https://github.com/kubernetes/kubernetes"